services:
  postgres:
    image: postgres:18
    container_name: whm-postgres
    environment:
      POSTGRES_DB: whm
      POSTGRES_USER: whm
      POSTGRES_PASSWORD: whm
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  iperf3:
    image: mlabbe/iperf3
    container_name: whm-iperf3
    command: -s
    ports:
      - "5201:5201"

volumes:
  postgres-data:
